2020-05-04 15:52:26,208 [DEBUG   ]    connectionpool.py(941):_new_conn            :: Starting new HTTPS connection (1): www.dynatrace.com:443
2020-05-04 15:52:26,513 [DEBUG   ]    connectionpool.py(442):_make_request        :: https://www.dynatrace.com:443 "GET /support/help/ HTTP/1.1" 200 None
2020-05-04 15:52:26,707 [INFO    ] api_permission_bot.py( 22):get_api_doc_list     :: Response is 200. Looking good!
2020-05-04 15:54:55,174 [DEBUG   ]    connectionpool.py(941):_new_conn            :: Starting new HTTPS connection (1): www.dynatrace.com:443
2020-05-04 15:54:55,531 [DEBUG   ]    connectionpool.py(442):_make_request        :: https://www.dynatrace.com:443 "GET /support/helpasdfas/ HTTP/1.1" 404 None
2020-05-04 15:55:31,173 [DEBUG   ]    connectionpool.py(941):_new_conn            :: Starting new HTTPS connection (1): www.dynatrace.com:443
2020-05-04 15:55:31,471 [DEBUG   ]    connectionpool.py(442):_make_request        :: https://www.dynatrace.com:443 "GET /support/helpasdfas/ HTTP/1.1" 404 None
2020-05-04 15:55:31,909 [ERROR   ] api_permission_bot.py( 21):get_api_doc_list     :: HTTP error occured: 404 Client Error: Not Found for url: https://www.dynatrace.com/support/helpasdfas/
2020-05-04 15:56:44,719 [DEBUG   ]    connectionpool.py(941):_new_conn            :: Starting new HTTPS connection (1): www.dynatrace.com:443
2020-05-04 15:56:45,028 [DEBUG   ]    connectionpool.py(442):_make_request        :: https://www.dynatrace.com:443 "GET /support/help/ HTTP/1.1" 200 78812
2020-05-04 15:56:45,225 [INFO    ] api_permission_bot.py( 25):get_api_doc_list     :: Response is 200. Looking good!
2020-05-04 15:57:29,219 [DEBUG   ]    connectionpool.py(941):_new_conn            :: Starting new HTTPS connection (1): www.dynatrace.com:443
2020-05-04 15:57:29,523 [DEBUG   ]    connectionpool.py(442):_make_request        :: https://www.dynatrace.com:443 "GET /support/help/ HTTP/1.1" 200 None
2020-05-04 15:57:29,708 [INFO    ] api_permission_bot.py( 25):get_api_doc_list     :: Response is 200. Looking good!
2020-05-04 15:57:55,494 [DEBUG   ]    connectionpool.py(941):_new_conn            :: Starting new HTTPS connection (1): www.dynatrace.com:443
2020-05-04 15:57:55,807 [DEBUG   ]    connectionpool.py(442):_make_request        :: https://www.dynatrace.com:443 "GET /support/help/ HTTP/1.1" 200 None
2020-05-04 15:57:55,998 [INFO    ] api_permission_bot.py( 25):get_api_doc_list     :: Response is 200. Looking good!
2020-05-04 16:03:20,605 [DEBUG   ]    connectionpool.py(941):_new_conn            :: Starting new HTTPS connection (1): www.dynatrace.com:443
2020-05-04 16:03:20,934 [DEBUG   ]    connectionpool.py(442):_make_request        :: https://www.dynatrace.com:443 "GET /support/help/ HTTP/1.1" 200 None
2020-05-04 16:03:21,128 [INFO    ] api_permission_bot.py( 27):get_api_doc_list     :: Response is 200. Looking good!
2020-05-04 16:08:54,862 [DEBUG   ]    connectionpool.py(941):_new_conn            :: Starting new HTTPS connection (1): www.dynatrace.com:443
2020-05-04 16:08:55,181 [DEBUG   ]    connectionpool.py(442):_make_request        :: https://www.dynatrace.com:443 "GET /support/help/ HTTP/1.1" 200 None
2020-05-04 16:08:55,290 [INFO    ] api_permission_bot.py( 32):get_api_doc_list     :: Response is 200. Looking good!
2020-05-04 16:12:15,700 [DEBUG   ]    connectionpool.py(941):_new_conn            :: Starting new HTTPS connection (1): www.dynatrace.com:443
2020-05-04 16:12:16,042 [DEBUG   ]    connectionpool.py(442):_make_request        :: https://www.dynatrace.com:443 "GET /support/help/ HTTP/1.1" 200 None
2020-05-04 16:12:16,279 [INFO    ] api_permission_bot.py( 32):get_api_doc_list     :: Response is 200. Looking good!
2020-05-04 16:18:56,416 [DEBUG   ]    connectionpool.py(941):_new_conn            :: Starting new HTTPS connection (1): www.dynatrace.com:443
2020-05-04 16:18:56,711 [DEBUG   ]    connectionpool.py(442):_make_request        :: https://www.dynatrace.com:443 "GET /support/help/ HTTP/1.1" 200 None
2020-05-04 16:18:56,855 [INFO    ] api_permission_bot.py( 32):get_api_doc_list     :: Response is 200. Looking good!
2020-05-04 16:20:15,906 [DEBUG   ]    connectionpool.py(941):_new_conn            :: Starting new HTTPS connection (1): www.dynatrace.com:443
2020-05-04 16:20:16,213 [DEBUG   ]    connectionpool.py(442):_make_request        :: https://www.dynatrace.com:443 "GET /support/help/ HTTP/1.1" 200 None
2020-05-04 16:20:16,362 [INFO    ] api_permission_bot.py( 32):get_api_doc_list     :: Response is 200. Looking good!
2020-05-04 16:20:41,445 [DEBUG   ]    connectionpool.py(941):_new_conn            :: Starting new HTTPS connection (1): www.dynatrace.com:443
2020-05-04 16:20:41,725 [DEBUG   ]    connectionpool.py(442):_make_request        :: https://www.dynatrace.com:443 "GET /support/help/ HTTP/1.1" 200 None
2020-05-04 16:20:41,868 [INFO    ] api_permission_bot.py( 32):get_api_doc_list     :: Response is 200. Looking good!
2020-05-04 16:22:37,063 [DEBUG   ]    connectionpool.py(941):_new_conn            :: Starting new HTTPS connection (1): www.dynatrace.com:443
2020-05-04 16:22:37,375 [DEBUG   ]    connectionpool.py(442):_make_request        :: https://www.dynatrace.com:443 "GET /support/help/ HTTP/1.1" 200 94775
2020-05-04 16:22:37,524 [INFO    ] api_permission_bot.py( 32):get_api_doc_list     :: Response is 200. Looking good!
2020-05-04 16:22:52,243 [DEBUG   ] api_permission_bot.py( 17):main                 :: Loaded soup from local storage
2020-05-04 16:23:22,044 [DEBUG   ] api_permission_bot.py( 17):main                 :: Loaded soup from local storage
2020-05-04 16:24:22,665 [DEBUG   ] api_permission_bot.py( 17):main                 :: Loaded soup from local storage
2020-05-04 16:26:01,143 [DEBUG   ] api_permission_bot.py( 18):main                 :: Loaded soup from local storage. Object type: <class 'bs4.BeautifulSoup'>
